// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MultiTracksAPI.Models
{
    public partial class AssessmentSteps
    {
        public int StepId { get; set; }
        public string Text { get; set; }
    }
}