CREATE TABLE dbo.Artist
(
	artistID INT PRIMARY KEY IDENTITY (1, 1),
	dateCreation SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	title VARCHAR(100) NOT NULL,
	biography VARCHAR(MAX) NOT NULL,
	imageURL VARCHAR(500) NOT NULL,
	heroURL VARCHAR(500) NOT NULL
)
